"""third migration

Revision ID: 5595ad14bcf5
Revises: b1aa54ade1f0
Create Date: 2020-05-11 17:56:58.296214

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5595ad14bcf5'
down_revision = 'b1aa54ade1f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_secondblogs_blogPost', table_name='secondblogs')
    op.drop_index('ix_secondblogs_user_id', table_name='secondblogs')
    op.drop_table('secondblogs')
    op.add_column('blogposts', sa.Column('posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blogposts', 'posted')
    op.create_table('secondblogs',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('blogTitle', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('blogPost', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='secondblogs_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='secondblogs_pkey')
    )
    op.create_index('ix_secondblogs_user_id', 'secondblogs', ['user_id'], unique=False)
    op.create_index('ix_secondblogs_blogPost', 'secondblogs', ['blogPost'], unique=False)
    # ### end Alembic commands ###
